version: '3'

services:
    auth:
        image: ramailh/centralized-auth-server
        ports:
            - "8080:8080"
        container_name: centralized-auth-server
        restart: always
        env_file: 
            - auth.env

    db:
        image: mongo
        ports:
            - 27017
        container_name: mongo
        restart: always
        volumes:
            - ./mongo/data:/data/db
